### PR TITLE
Added map and histogram to stats view

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Adds a map and a datetime histogram using Bokeh to view interview data. 
Can also filter by state or time interview was submitted/modified. 

View looks like this (with test data):
Screenshot from 2021-01-11 13-22-16

### CODE REVIEW

**Comment by nonprofittechy** [comment]
Can you add `bokeh` and `cenpy` as dependencies on the packages page, so those two at least will install automatically? I know we have the issue of manually needing to install `libspatialindex-dev` debian package

**Comment by nonprofittechy** [comment]
One more thought: state should be optional, as we won't record state for most of our interviews (they are MA only)

**Comment by BryceStevenWilley** [comment]
> Can you add bokeh and cenpy as dependencies on the packages page, so those two at least will install automatically?

Do you mean the packages page in docassemble (I'm assuming dev/prod, they're already there in test), or the requirements.txt in this package?

**Comment by nonprofittechy** [comment]
the 

> 
> 
> > Can you add bokeh and cenpy as dependencies on the packages page, so those two at least will install automatically?
> 
> Do you mean the packages page in docassemble (I'm assuming dev/prod, they're already there in test), or the requirements.txt in this package?

Playground | Packages, you can select individual Python packages that will install from pyPI when the package is installed.

**Pull request merged**
